### ISSUE TITLE
Map pins occasionally seem to get stuck with no way to remove them

### ISSUE THREAD

**Issue by NoShotz** [Nercus/MapPinEnhanced#22] opened 2024-08-23 18:11 UTC
When setting a map pin via other addons like rare scanner, you can get pins that don't get removed properly, you go to remove it, but a pin remains in the world that can't be removed. 

![image](https://github.com/user-attachments/assets/4fd9cb9d-1e11-458f-babb-b9c87f4f0fc1)

Additionally pins set like this don't have the travel time on em even though I have it turned on, and I have seen other situations where that is the case. 

It seems what may be happening is when pins are set by other addons, they automatically get tracked, but aren't being tracked by this addon as the pin appears in the world space, but doesn't show the time to travel there or the name until I click the map pin in the world to make it gold instead of bronze.

Here's a video of this happening where I use the key combo of placing a map pin for the map icons rare scanner adds, https://streamable.com/fxhvd9

Unrelated to this, but I swear quest provided navigation markers used to have the travel time on them as well when using this addon.

**Comment by NoShotz** [comment] 2024-08-23 18:49
I just found the exact cause of the map pin becoming stuck, if you add a map pin like in the video, but don't click on it to make it gold, instead just removing it, it gets stuck.

**Comment by Nercus** [comment] 2024-08-24 07:48
Thanks for the videos they helped a lot. Unfortunately, there is a bug right now in Map Pin Enhanced, where newly created pins are not tracked automatically. That behavior leads to other weird interactions and also the one you experienced. I have not figured out the cause for it yet though as I have not found a reliable way to reproduce it. 

> Unrelated to this, but I swear quest provided navigation markers used to have the travel time on them as well when using this addon.

It will be brought back!

**Comment by Nercus** [comment] 2024-12-17 19:20
Should be fixed in the new version

**Closed by Nercus** 2024-12-17 19:20 UTC
Labels: bug
